/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift16_13 (
    input [15:0] a,
    input [15:0] b,
    input [4:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn)
      5'h18: begin
        out = a << b[0+3-:4];
      end
      5'h19: begin
        out = a >> b[0+3-:4];
      end
      5'h1a: begin
        out = $signed(a) >>> b[0+3-:4];
      end
    endcase
  end
endmodule
