/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module test_boole_3 (
    input clk,
    input rst,
    input start,
    output reg [1:0] status
  );
  
  
  
  reg [3:0] M_test_counter_d, M_test_counter_q = 1'h0;
  
  
  localparam IDLE_state = 2'd0;
  localparam TEST_state = 2'd1;
  localparam PASS_state = 2'd2;
  localparam FAIL_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = IDLE_state;
  
  wire [16-1:0] M_boole16_out;
  reg [16-1:0] M_boole16_a;
  reg [16-1:0] M_boole16_b;
  reg [5-1:0] M_boole16_alufn;
  boole16_12 boole16 (
    .a(M_boole16_a),
    .b(M_boole16_b),
    .alufn(M_boole16_alufn),
    .out(M_boole16_out)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_test_counter_d = M_test_counter_q;
    
    status = 1'h0;
    M_boole16_a = 1'h0;
    M_boole16_b = 1'h0;
    M_boole16_alufn = 5'h10;
    if (start == 1'h0) begin
      M_state_d = IDLE_state;
    end
    
    case (M_state_q)
      IDLE_state: begin
        status = 1'h0;
        if (start == 1'h1) begin
          M_state_d = TEST_state;
        end
      end
      TEST_state: begin
        
        case (M_test_counter_q)
          4'h0: begin
            M_boole16_alufn = 5'h12;
            M_boole16_a = 16'h1234;
            M_boole16_b = 16'h4321;
            if (M_boole16_out != 16'h0220) begin
              M_state_d = FAIL_state;
            end
          end
          4'h1: begin
            M_boole16_alufn = 5'h14;
            M_boole16_a = 16'h1234;
            M_boole16_b = 16'h4321;
            if (M_boole16_out != 16'h5335) begin
              M_state_d = FAIL_state;
            end
          end
          4'h2: begin
            M_boole16_alufn = 5'h16;
            M_boole16_a = 16'h1234;
            M_boole16_b = 16'h4321;
            if (M_boole16_out != 16'h5115) begin
              M_state_d = FAIL_state;
            end
          end
          4'h3: begin
            M_boole16_alufn = 5'h13;
            M_boole16_a = 16'h1234;
            M_boole16_b = 16'h4321;
            if (M_boole16_out != 16'hfddf) begin
              M_state_d = FAIL_state;
            end
          end
          4'h4: begin
            M_boole16_alufn = 5'h15;
            M_boole16_a = 16'h1234;
            M_boole16_b = 16'h4321;
            if (M_boole16_out != 16'hacca) begin
              M_state_d = FAIL_state;
            end
          end
          4'h5: begin
            M_boole16_alufn = 5'h17;
            M_boole16_a = 16'h1234;
            M_boole16_b = 16'h4321;
            if (M_boole16_out != 16'h1234) begin
              M_state_d = FAIL_state;
            end
          end
          4'h7: begin
            M_state_d = PASS_state;
          end
        endcase
      end
      PASS_state: begin
        status = 1'h1;
      end
      FAIL_state: begin
        status = 2'h2;
      end
    endcase
    M_test_counter_d = M_test_counter_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_test_counter_q <= 1'h0;
    end else begin
      M_test_counter_q <= M_test_counter_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
